"""empty message

Revision ID: 5419c5831f07
Revises: 
Create Date: 2021-12-22 13:30:47.637817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5419c5831f07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('software', 'tags')
    # ### end Alembic commands ###
